const plantTypes = [
  {
    id: 0,
    type: 'Echeveria(Succulent)',
    soil: 'Moderately acid (5.6 – 6.0) Slightly acid (6.1 – 6.5) Neutral (6.6 – 7.3) Slightly alkaline (7.4 – 7.8)',
    minColdHard: 'Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)',
    leaves: 'Unusual foliage color, Evergreen',
    sun: 'Partial or Dappled Shade',
    flowers: 'Showy',
    flowerColor: 'Other: Pinkish red',
    bloomSize: 'Under 1"',
    suitableLocations: 'Xeriscapic, Houseplant',
    propMethods: 'Cuttings: Leaf',
    otherMethods: 'Offsets',
    containers: 'Suitable in 1 gallon, Needs excellent drainage in pots',
    link: 'https://garden.org/plants/view/111967/Echeveria-Perle-von-Nurnberg/',
  },
  {
    id: 1,
    type: 'Mentha x piperita(Peppermint)',
    sun: 'Full Sun to Partial Shade',
    leaves: 'Unusual foliage color, Fragrant', 
    flowers: 'Showy, Fragrant',
    suitableLocations: 'Bog gardening',
    propMethods: 'Cuttings: Stem',
    otherMethods: 'Division, Stolons and runners',
    containers: 'Suitable in 1 gallon, Suitable in 3 gallon or larger',
    link: 'https://garden.org/plants/view/144515/Peppermint-Mentha-x-piperita/',
  },
  {
    id: 2,
    type: 'Rosa(Rose)',
    sun: 'Full Sun',
    soil: 'Moderately acid (5.6 – 6.0) Slightly acid (6.1 – 6.5) Neutral (6.6 – 7.3) Slightly alkaline (7.4 – 7.8)',
    leaves: 'Deciduous',
    flowers: 'Showy',
    propMethods: 'Cuttings: Stem',
    otherMethods: 'Cuttings: Tip',
    link: 'https://garden.org/plants/view/181506/Roses-Rosa/',
  },
  {
    id: 3,
    type: 'Goeppertia orbifolia(Calathea)',
    sun: 'Partial or Dappled Shade',
    water: 'Mesic',
    soil: 'Moderately acid (5.6 – 6.0) Slightly acid (6.1 – 6.5) Neutral (6.6 – 7.3) Slightly alkaline (7.4 – 7.8)',
    leaves: 'Unusual foliage color, Evergreen, Other: Rounded in shape; upper surface silver and green stripes; lower surface, pale green.',
    flowers: 'Showy',
    suitableLocations: 'Houseplant',
    containers: 'Needs excellent drainage in pots',
    link: 'https://garden.org/plants/view/333848/Prayer-Plant-Goeppertia-orbifolia/',
  },
  {
    id: 4,
    type: 'Gerbera(Transvaal daisy)',
    sun: 'Full Sun',
    water: 'Mesic, Dry Mesic',
    soil: 'Slightly acid (6.1 – 6.5) Neutral (6.6 – 7.3)',
    leaves: 'Evergreen',
    flowers: 'Showy, Flagrant',
    flowerTime: 'Spring, Late spring or early summer, Summer, Late summer or early fall, Fall',
    propMethods: 'Cuttings: Stem',
    otherMethods: 'Division',
    containers: 'Suitable in 3 gallon or larger, Needs excellent drainage in pots',
    link: 'https://garden.org/plants/view/712791/African-Daisy-Osteospermum-ecklonis-Serenity-Blue-Eyed-Beauty/',
  },
  {
    id: 5,
    type: 'Leucanthemum × superbum(Shasta daisy)',
    sun: 'Full Sun, Full Sun to Partial Shade',
    water: 'Mesic, Dry Mesic',
    flowers: 'Showy',
    flowerColor: 'White',
    bloomSize: '2"-3"',
    flowerTime: 'Spring, Summer, Fall',
    suitableLocations: 'Xeriscapic',
    link: 'https://garden.org/plants/view/530761/Shasta-Daisy-Leucanthemum-x-superbum-Daisy-May/',
  },
  {
    id: 6,
    type: 'Herb',
    sun: 'Partial or Dappled Shade',
    soil: 'Slightly acid (6.1 – 6.5) Neutral (6.6 – 7.3)',
    minColdHard: 'Zone 13 +15.6 °C (60 °F) to +21.1 °C (70 °F)',
    leaves: 'Evergreen',
    flowers: 'Showy',
    flowerColor: 'White, Other: Creamy white spathe, pale yellow spadix.',
    suitableLocations: 'Houseplant',
    propMethods: 'Division',
    imageSrc: 'http://localhost:9000/images/agm-notfound.png', //'/assets/Succulent.jpg', 
    imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
    state: "error",
    water: 'Mesic',
    containers: 'Needs excellent drainage in pots',
    link: 'https://garden.org/plants/view/119743/Peace-Lily-Spathiphyllum-cannifolium/',   
  },
  {
    id: 7,
    type: 'Adiantum capillus-veneris(Fern)',
    sun: 'Partial or Dappled Shade, Partial Shade to Full Shade',
    water: 'Mesic',
    minColdHard: 'Zone 5b -26.1 °C (-15 °F) to -23.3 °C (-10 °F)',
    leaves: 'Deciduous',
    suitableLocations: 'Terrariums, Bog gardening',
    propMethods: 'Division',
    containers: 'Suitable for hanging baskets, Needs excellent drainage in pots',
    link: 'https://garden.org/plants/view/75129/Southern-Maidenhair-Fern-Adiantum-capillus-veneris/',
  },{
    id: 8,
    type: 'Abies(Fir)',
    sun: 'Full Sun',
    soil: 'Acidic (pH < 6.0)',
    minColdHard: 'Varies by species',
    leaves: 'Evergreen, needle-like leaves',
    flowers: 'Cones',
    suitableLocations: 'Mountains',
    propMethods: 'Seeds',
    otherMethods: 'N/A',
    containers: 'Not suitable for containers',
    link: 'https://conifersociety.org/conifers/abies/',
},
{
    id: 9,
    type: 'Acacia(Wattles)',
    sun: 'Full Sun to Partial Shade',
    soil: 'Well-drained soil',
    minColdHard: 'Varies by species',
    leaves: 'Evergreen, some species have phyllodes or cladodes instead of leaves',
    flowers: 'Showy, often in clusters',
    suitableLocations: 'Varies by species',
    propMethods: 'Seeds',
    otherMethods: 'N/A',
    containers: 'Varies by species',
    link: 'https://garden.org/plants/browse/plants/genus/Acacia/',
},
];




export { plantTypes };